default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: nuclear_rules_development

test:
  <<: *default
  database: nuclear_rules_test

production:
  <<: *default
  database: nuclear_rules_production
  username: nuclear_rules
  password: <%= ENV['NUCLEAR_RULES_DATABASE_PASSWORD'] %>
